### ISSUE TITLE
[Feature Request] Command Line Option for adjusting smoothing

### ISSUE THREAD

**Issue by 21LeYe** [tommyettinger/spotvox#2]
#### Spotvox Version: 0.0.4 (Windows)

I enjoy using SpotVox to create sprites at 4x scale as it has the level of detail I require. However, I notice at 4x scale, the program tends to create smooth corners at unwanted areas. I've been using a semi-workaround by taking away a few voxels at the problematic areas but this only reduces the issue instead of fixing it, and can be somewhat prone to strange geometry. 

Would it be possible to add a command line option to adjust smoothing at higher scales? This would allow users to create higher scale sprites while retaining the blockiness of scale 1x. 

I am unsure if I have conveyed my issue accurately, so I have created a diagram to help illustrate the problem.

### Screenshot
![Untitled(2)](https://user-images.githubusercontent.com/49247040/199868344-c806f900-5be2-477c-8bd3-55ce2060e0c4.png)

**Comment by tommyettinger** [comment]
Does using the command-line argument `-m -4` do what you want? Negative values for multiples are treated as "blocky multiples" rather than "smooth multiples." This is documented, but it's quite easy to miss, especially since I didn't post a blocky-multiplied image as a preview in the README.md .

Here's a smiling bear at 8x size, produced with the extra option `-m -4`  (the negative number doesn't indicate negative scale):
![Bear_angle0](https://user-images.githubusercontent.com/160684/200104599-4f765312-df79-49b1-8c66-4700830e1e13.png)

Here's the same bear using the default smoothing, using `-m 4` (positive):
![Bear_angle0](https://user-images.githubusercontent.com/160684/200104647-d649c30d-9f12-4951-8d75-e4ee9bbd6d72.png)

Blocky multiples don't look as sharp-edged as they could, just because of how lighting is handled. I think changing the Material options in the .vox file can be used to make edges look less rounded off. Right now, when a voxel would receive light from a light source above (like the sky; a strong light source) and also from the left side (which is a weak light source), that voxel has its lightness become extra-bright based on the material's IOR and possibly Roughness values (lower values for both make the edges less bright; you may need to change the material to Blend type to access IOR).

As a preview of an upcoming feature, here's a turntable gif of the 8x blocky-scaled bear:
![Bear_Turntable](https://user-images.githubusercontent.com/160684/200105910-f0ff6334-cefe-4669-9117-db52cc5e10e1.gif)

**Comment by 21LeYe** [comment]
![rattata_angle0](https://user-images.githubusercontent.com/49247040/200138213-ea48bac2-06d5-4d18-9bbb-a065d18b6e85.gif)

Wow, I completely missed that you can do numbers larger than -1. This is perfect, thank you so much!
