### ISSUE TITLE
Export All Angles?

### ISSUE THREAD

**Issue by WelfareCheckVS** [tommyettinger/spotvox#3]
Love the tool! 

Not sure if this is currently possible? I don't see that it is.

Would it be possible to export 360 angle sprites for a model? I'd like to load all 360 to a dictionary and use the one for my current angle. 

Maybe an additional option for every 2nd, 4th, 8th, 15th, etc. angle as well so others who don't want so many sprites have an option to do something similar. Easily divisible sets. 

Thank you!

**Comment by tommyettinger** [comment]
It's definitely possible in a future release, and might not even be very hard for me to add. Right now, any turntable requires drawing 128 images that get put into one GIF animation; only the frames per second number changes if users want slower or faster rotations through that sequence of 128. There's nothing specifically in the code that requires 128, I just couldn't see much change with smaller rotations. That means right now, 128 images are generated, put into the GIF, and discarded without writing them to file individually. The option here would just allow writing some amount of images to file individually. Any complete rotation at a constant speed should be do-able with very few changes, as long as the user specifies how many images they want. In your case, that sounds like 360, but even something weird like 43 images should work, though it wouldn't be perfectly grid-aligned except maybe at the start.

I'll start tinkering with this now, I think.

**Comment by tommyettinger** [comment]
I believe this is complete, less than half an hour later! I should make some samples that use it, but for now, here are two zips of PNGs, one of 360 rotations, one of 43.
[Copter43.zip](https://github.com/tommyettinger/spotvox/files/10608249/Copter43.zip)
[EyeTyrant360.zip](https://github.com/tommyettinger/spotvox/files/10608252/EyeTyrant360.zip)
The usage just adds a -r or --rotations option, which defaults to 8. The behavior before always produced 8 rotations, and now you can produce just 4, 360, or whatever number as long as it is greater than 0. That's the count of rotations produced for each size, so instead of the old default of 8 rotations at size 1, 8 rotations at size 2, and so on, those could be 360 rotations at size 1 and 360 rotations at size 2. If this sounds like what you want, I'll push a release with it next afternoon. (That's 12-18 hours from now, maybe?)

**Comment by WelfareCheckVS** [comment]
That is beautiful! Below is a gif for a quick pass of what I wanted to accomplish. Model isn't oriented and centered but it looks really good with nice smooth rotation. 

Take your time! Glad it wasn't too time consuming. I had tried exporting to turn table and then from gif to individual images but the resolution drop was 50% and it looked terrible. So, this will be exponentially better!

Really appreciate your fast turnaround! I was about to make this in 3D instead of iso because of the 8 slice and how rigid it looked. 

A* controlled
![Unity_CTjwKFFZ4Q](https://user-images.githubusercontent.com/100054224/216772711-8431fcaa-23a5-4514-8631-a4646ab0b0fb.gif)

Player controlled
![Unity_BeFGRrv12U](https://user-images.githubusercontent.com/100054224/216775106-bc44ee44-572e-484f-9347-d54f3dc39cd8.gif)

**Comment by 21LeYe** [comment]
exciting release, can't wait to make 16 rotation sprites!

**Comment by tommyettinger** [comment]
This should be fixed now that release 0.0.6 is out. Those rotating Eye Tyrants look great!
